* [1/1] Управление темой
 - [X] продумать структуру конфигурации темы
	В файле theme.lua задаются настройки для необходимых модулей,
	после чего в цикле вызывается функция apply для каждого модуля.
	Аргументами функции являются заданные в теме настройки модуля.
	Модули лежат в .config/awesome/lib.
** [2/2] [[./lib/actions.lua]]
   Модуль, содержащий разные вспомогательные функции, которые 
   модифицируют/заменяют файлы конфигураций общего вида (не специальные)
   - [X] вынести в отдельный файл 
   - [X] сделать вывод настроек в файл, определяемый в конфигурации темы 
** [/] [[./lib/acyl.lua]]
   Модуль для acyl-а
   - [ ] сделать вывод прочитанных парсером данных в xml файл
   - [ ] выяснить, возможно ли сделать так, чтобы иконки экспортировались 
	 один раз в директорию темы, а затем, при каждом перезапуске - 
	 обновлялись бы, проверяя директорию, указанную в качестве
	 содержащей исходные иконки, на наличие новых и перекрашивались
	 бы, если в теме так указано
** [1/5] [[./lib/palette.lua]]
   Модуль управления палитрой. Содержит функции парсинга файла палитр GIMP и функции
   модификации цветов. При применении ничего не происходит.
   - [ ] добавить shade
   - [ ] добавить mix
   - [ ] посмотреть в доках GTK что ещё добавить и добавить это
   - [ ] добавить возможность задавать два имени для одного цвета, например,
	 разделяя их запятой
   - [X] прибраться
   
	 
