* О *проекте*
  Этот *проект* ставит целью создать общие и специальные средства 
  для управления параметрами отображения разных программ, путём
  изменения их конфигурационных файлов в соответствии с настрой-
  ками, указанными в файле конфигурации *проекта*.
  
* Этапы выполнения *проекта*
   1. Реализация *проекта*, как надстройки для системы управления
      темами оконного менеджера awesome. Т.о. на первом этапе
      в качестве файла конфигурации *проекта* выступает файл конфи-
      гурации темы awesome.
   2. Реализация *проекта*, как общего решения, не зависящего от
      инфраструктуры какого-то конкретного оконного менеджера.

** Первый этап
   Далее: 
   - /курсивом/ обозначаются термины, действительные в рамках
     первого этапа проекта.
   - _подчёркиванием_ обозначаются параметры функций

   - /конфигурация/ - это таблица lua, содержащая все сведения,
     необходимые для формирования и применения настроек конфигу-
     рируемой с помощью *проекта* программы.
   - /настройки конфигурации/ - подтаблица таблицы /конфигурация/,
     содержащая сведения, являющиеся настройками для конфигури-
     руемой с помощью *проекта* программы

*** Файлы на первом этапе выполнения *проекта*
    *Проект* на первом этапе его выполнения представляет собой рабочую
    конфигурацию оконного менеджера awesome.
    - [[./lib/palette.lua]] - работа с палитрой GIMP (пока что только её чтение)
    - [[./lib/actions.lua]] - действия общего рода по применению /конфигураций/
    - [[./lib/configs.lua]] - работа с /настройками конфигураций/ (получение 
      строк из /настроек конфигураций/)
    - [[./lib/acyl.lua]]    - то, что относится к /конфигурации/ темы иконок 
      Any Color You Like
    - [[./lib/utils.lua]]   - вспомогательные функции
    - [[./lib/vardump.lua]] - вывод таблиц (для отладки)

    - [[./themes/medusa/theme.lua]] - рабочий файл настроек темы awesome
    - [[./rc.lua]]                  - рабочий файл настроек awesome

    - [[./README.org]]      - этот файл

*** Как это должно работать на первом этапе
    При инициализации темы awesome читается файл палитры GIMP,
    содержащий цвета, которые будут использованы в теме awesome
    и в настройках разных программ, определяемых в файле темы awesome
    особым образом.
    

    Все /конфигурации/ содержатся в таблице theme.configs, определяемой
    в файле темы awesome. /Конфигурация/ состоит из следующего:
    - files = {} -- таблица, содержащая все файлы, которые должны быть
      изменены\переписаны в соответствии с заданными /настройками конфигурации/.
    - funcs = {} -- таблица, содержащая ссылки на все функции, которые
      нужно выполнить по порядку для применения /настроек конфигурации/.
      Каждая из этих функций получает в качестве аргумента /конфигурацию/,
      к которой принадлежит. Эти функции специфичны для /конфигурации/, в 
      которой указаны. Хотя некоторые из них (как actions.writeFile) достаточно
      общи для того, чтобы их можно было запускать для разных конфигураций.
    - data = {} -- таблица, содержащая /настройки конфигурации/ - т.е. те
      сведения, из которых, через преобразования с помощью функций, задан-
      ных в funcs, получится таблица строк, которые и представляют собой
      настройки соответствующей программы. Эти строки затем могут обрабатываться
      далее в оставшихся для выполнения функциях из funcs.
    - strings = {} -- таблица, содержащая все строки /настроек конфигурации/,
      которые должны быть так или иначе применены (записаны в файл, экспортированы,
      как содержимое переменной окружения и т.д.) с помощью одной из последних
      функций в funcs.

*** TODO [5/9]
    - [X] [[./lib/pallete.lua]] интегрировать colors.lua
    - [X] [[./lib/pallete.lua]] добавить возможность задавать несколько
	  имён для одного цвета, например, разделяя имена запятыми
	  в файле палитры.
    - [ ] [[./lib/actions.lua]] добавить функции для экспорта 
	  _переменных окружения_ и для замены части файла, 
	  ограниченной _начальным куском_ и _конечным куском_
    - [X] [[./lib/configs.lua]] переместить функцию синхронизации xrdb в
	  [[./lib/actions.lua]]
    - [X] [[./lib/acyl/lua]] определить состав /конфигурации/
    - [ ] [[./lib/acyl.lua]] добавить генерацию нужного svg-куска из /конфигурации/
    - [ ] [[./lib/acyl.lua]] добавить копирование отсутствующих в теме иконок из 
	  _каталога-источника_ в _каталог-приёмник_ внутри каталога темы
    - [ ] [[./lib/acyl.lua]] добавить создание симлинков для текущей темы иконок
	  в _каталоге симлинков_ (.icons/awesome-icon-theme по-умолчанию)
    - [X] [[./lib/acyl.lua]] добавить функцию формирования списка файлов
